import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(17,GPIO.OUT)
GPIO.setup(18,GPIO.OUT)
GPIO.setup(22,GPIO.OUT)
GPIO.setup(23,GPIO.OUT)
#GPIO.cleanup()
#time.sleep(1)
print ("LED 17 on")
GPIO.output(17,GPIO.HIGH)
time.sleep(1)
print ("LED 18 on")
GPIO.output(18,GPIO.HIGH)
time.sleep(1)
print ("LED 22 on")
GPIO.output(22,GPIO.HIGH)
time.sleep(1)
print ("LED 23 on")
GPIO.output(23,GPIO.HIGH)
time.sleep(1)

GPIO.output(17,GPIO.LOW)
GPIO.output(18,GPIO.LOW)
GPIO.output(22,GPIO.LOW)
GPIO.output(23,GPIO.LOW)

GPIO.cleanup()
